name: Run Flutter Tests

on:
    push:
        branches: 
            - main
    pull_request:
        branches: 
            - main

        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2.12.0
              with: 
                channel: 'stable'
                flutter-version: '3.16.5'
            - run: flutter clean
            - run: flutter pub get


            

        
